apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-web
    role: backend
  name: hello-web-app
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: hello-web
    role: backend
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-web
    role: backend
  name: hello-web-app
spec:
  selector:
    matchLabels:
      app: hello-web
      role: backend
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hello-web
        role: backend
      name: app
    spec:
      containers:
      - env:
        - name: ENVIRONMENT
          value: dev
        - name: LOG_LEVEL
          value: info
        image: gcr.io/qwiklabs-gcp-01-9def547ff255/hello-web:v1@sha256:05879b78e4b85d84058ce2e231468ef05b42256efafd0bdefd98964886a9ba01
        name: app
        ports:
        - containerPort: 8080
          name: http
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 1
          periodSeconds: 1
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 25m
            memory: 64Mi
